feat(journey-maps)
sbb-design-systems/sbb-angular pull request #1285
Opened 2022-03-15 10:48 UTC by mstankala

2022-03-15 14:05 UTC, mstankala commented
@kyubisation the api_key is not available/configured in the staging showcaseApp. Can you support me?

2022-03-24 18:12 UTC, kyubisation requested changes
Some general feedback:
- We prefix our symbols (classes, constants, interfaces) with Sbb* or SBB_* and don't use the *Component, *Directive and *Service suffix. (e.g. `JourneyMapsClientComponent` => `SbbJourneyMapsClient`)
- The internal components still use the rokas selector prefix. Is this intended?
- Documentation is generally lacking. Is this really enough?

2022-03-28 08:34 UTC, mstankala commented on src/journey-maps/angular/angular.md
> +`<sbb-journey-maps language="en" apiKey="<API-KEY>"></sbb-journey-maps>` displays an interactive map, with rail-specific style.
The Documenation-Story is planed in next PI.

2022-04-01 08:30 UTC, sebisteiner commented on src/components-examples/journey-maps/angular/angular/angular-example.ts
> +import { zhShWaldfriedhof } from './test-data/journey/zh-sh_waldfriedhof';
Yes. The data should be a blackbox for the regular user. He receives it from our backend (Journey Maps) and puts it directly into Journey Maps Client.

2022-04-01 09:09 UTC, sebisteiner commented on src/journey-maps/angular/components/leit-poi/model/leit-poi-placement.ts
> +export enum LeitPoiPlacement {
We kept `MarkerCategory` and `MarkerPriority` and replaced the rest with union types.

2022-04-01 14:24 UTC, sebisteiner commented
> Documentation is generally lacking. Is this really enough?

I created some more documentation.

IMO we should split up the full example into multiple, smaller ones that showcase each one a different piece of functionality.

But for the moment I think we can start with what we have now.

2022-04-05 11:45 UTC, kyubisation requested changes
Some additional notes, but looks much closer to done.
Thanks for your work!

2022-04-05 11:45 UTC, kyubisation commented on src/journey-maps/angular/components/popup/popup.scss
> +// Popup style needs to be global
Nitpick: Why not simply declare global popup styles here and disable view encapsulation for this component?

2022-04-08 10:26 UTC, kyubisation approved these changes
LGTM 👍 
Thank you for your adaptations!

2022-04-08 10:38 UTC, merged