fix(angular/datepicker): fix Voiceover losing focus on PageDown
sbb-design-systems/sbb-angular pull request #1286
Opened 2022-03-15 10:51 UTC by mhaertwig

Add a timeout before programmatically focusing cells on the calendar. This seems to fix an issue where Voiceover loses focus when pressing the PageDown/PageUp keys.

2022-03-16 10:19 UTC, jeripeierSBB requested changes

2022-03-16 10:19 UTC, jeripeierSBB commented on src/angular/datepicker/calendar-body/calendar-body.ts
> +   * (issue #24330).
```suggestion
   * (issue angular/components#24330).
```

2022-03-18 19:02 UTC, kyubisation approved these changes
LGTM 👍 
(Except for what @jeripeierSBB pointed out)

2022-03-21 08:32 UTC, jeripeierSBB approved these changes
LGTM

2022-03-21 10:47 UTC, merged