fix(angular/dialog): provide defaults for dialog animation
sbb-design-systems/sbb-angular pull request #1287
Opened 2022-03-15 11:17 UTC by mhaertwig

Even though we provide defaults when we construct the animation object, some internal cases break because there are no defaults in the animation definition itself. These changes provide the defaults in the animation definition as well.

2022-03-16 10:20 UTC, jeripeierSBB approved these changes
LGTM, but also here, don't forget lightbox adaption.

2022-03-16 16:21 UTC, jeripeierSBB requested changes

2022-03-16 16:21 UTC, jeripeierSBB commented on src/angular/dialog/dialog-container.ts
> +        exitAnimationDuration:
```suggestion
        'exitAnimationDuration':
```

2022-03-16 16:22 UTC, jeripeierSBB commented on src/angular/dialog/dialog-container.ts
> +        enterAnimationDuration:
see https://github.com/angular/components/commit/575332c9296c28776376f4b4f7fb39c9743761aa

2022-03-21 09:50 UTC, kyubisation approved these changes
LGTM 👍

2022-03-21 10:21 UTC, jeripeierSBB approved these changes
LGTM

2022-03-21 10:32 UTC, merged