docs(angular/table): add example for expandable table
sbb-design-systems/sbb-angular pull request #1355
Opened 2022-03-31 10:57 UTC by mhaertwig

2022-04-01 13:18 UTC, kyubisation approved these changes
LGTM 👍

2022-04-04 05:37 UTC, jeripeierSBB requested changes
I think it would be better to let the expanded state be toggleable, what do you think?

2022-04-04 05:37 UTC, jeripeierSBB commented on src/components-examples/angular/table/expandable-table/expandable-table-example.html
> +<p>This table uses the when predicate for expanding and collapsing detail columns on row click.</p>
```suggestion
<p>This table uses the 'when'-predicate for expanding and collapsing detail columns on row click.</p>
```

2022-04-04 05:37 UTC, jeripeierSBB commented on src/components-examples/angular/table/expandable-table/expandable-table-example.html
> +    <!-- Expanded content column - The detail row is made up of this one column -->
```suggestion
    <!-- Expanded content column - The detail row is made up of this single column -->
```

2022-04-04 05:37 UTC, jeripeierSBB commented on src/components-examples/angular/table/expandable-table/expandable-table-example.html
> +      <th sbb-header-cell *sbbHeaderCellDef>Zeit</th>
```suggestion
      <th sbb-header-cell *sbbHeaderCellDef>Time</th>
```

2022-04-04 05:37 UTC, jeripeierSBB commented on src/components-examples/angular/table/expandable-table/expandable-table-example.html
> +      <th sbb-header-cell *sbbHeaderCellDef>Verbindung Bern - Olten</th>
```suggestion
      <th sbb-header-cell *sbbHeaderCellDef>Connection Bern - Olten</th>
```

2022-04-04 05:37 UTC, jeripeierSBB commented on src/components-examples/angular/table/expandable-table/expandable-table-example.html
> +      <th sbb-header-cell *sbbHeaderCellDef>Dauer</th>
```suggestion
      <th sbb-header-cell *sbbHeaderCellDef>Duration</th>
```

2022-04-04 05:37 UTC, jeripeierSBB commented on src/components-examples/angular/table/expandable-table/expandable-table-example.ts
> +const TABLE_EXAMPLE_DATA = [
Can you please translate example data in english? thank you :)

2022-04-04 05:37 UTC, jeripeierSBB commented on src/components-examples/angular/table/expandable-table/expandable-table-example.ts
> +  { id: 3, detailRow: true, changes: 0, details: 'Bern, Gleis 12; Olten, Gleis 4' },
Maybe one item should be not expansible to demonstrate the function above?

2022-04-04 12:04 UTC, jeripeierSBB approved these changes
LGTM

2022-04-04 12:48 UTC, merged