refactor(angular/dialog): use embedded injector to provide ref to template dialogs
sbb-design-systems/sbb-angular pull request #1371
Opened 2022-04-05 07:56 UTC by jeripeierSBB

Previously we had to walk the DOM in order to figure out which dialog ref belonged to a specific template dialog. We no longer need to do that if we provide an injector to the template portal.

BREAKING CHANGE:
depends on @angular/cdk 14

2022-04-05 10:03 UTC, kyubisation requested changes

2022-04-05 10:03 UTC, kyubisation commented on src/angular/dialog/dialog.ts
> +            dialogRef,
I think this change broke the lightbox test.
Attempted fix:
```suggestion
            dialogRef,
            lightboxRef: dialogRef,
```

2022-04-05 11:59 UTC, kyubisation approved these changes
LGTM 👍

2022-04-06 06:43 UTC, mhaertwig approved these changes
LGTM 👍

2022-04-06 06:44 UTC, merged