docs: describe v14 update steps
sbb-design-systems/sbb-angular pull request #1503
Opened 2022-06-08 14:32 UTC by mhaertwig

- Dynamic generation of update page
- Describe update to v14

2022-06-09 05:56 UTC, jeripeierSBB requested changes

2022-06-09 05:56 UTC, jeripeierSBB commented on src/showcase/app/app.module.ts
> +import { FormsModule, ReactiveFormsModule } from '@angular/forms';
FormsModule is not needed I think?

2022-06-09 05:56 UTC, jeripeierSBB commented on src/showcase/app/howtoupdate/update-steps.ts
> +        <pre>npx @angular/cli@13 update @angular/core@${version} @angular/cli@${version} --force</pre>`,
```suggestion
        <pre>npx @angular/cli@${version} update @angular/core@${version} @angular/cli@${version} --force</pre>`,
```

2022-06-09 14:36 UTC, kyubisation approved these changes
LGTM 👍

2022-06-09 14:40 UTC, jeripeierSBB approved these changes
LGTM

2022-06-13 09:15 UTC, mhaertwig commented on src/showcase/app/howtoupdate/update-steps.ts
> +      <p>Additionally, you have to prefix all imported symbols: e.g. <code>pxToRem(3)</code> becomes <code>sbb.pxToRem(5)</code></p>
```suggestion
      <p>Additionally, you have to prefix all imported symbols: e.g. <code>pxToRem(5)</code> becomes <code>sbb.pxToRem(5)</code></p>
```

2022-06-13 09:17 UTC, merged