feat(journey-maps): v1 route hover
sbb-design-systems/sbb-angular pull request #1829
Opened 2023-02-23 12:44 UTC by mstankala

2023-02-23 13:57 UTC, swiss-chris commented
@mstankala machst du auch noch diesen Change hier?

https://github.com/sbb-design-systems/sbb-angular/pull/1828#discussion_r1115587307

2023-02-23 13:57 UTC, swiss-chris requested changes
@mstankala machst du auch noch diesen change hier ?

https://github.com/sbb-design-systems/sbb-angular/pull/1828#discussion_r1115587307

2023-02-24 07:40 UTC, sebisteiner approved these changes
LGTM

2023-03-08 13:45 UTC, mstankala commented
> 

Done

2023-03-08 13:49 UTC, swiss-chris commented on src/components-examples/journey-maps/angular/journey-maps-full/journey-maps-full-example.ts
> +        if (this.journeyMapsRoutingOption?.journey) {
👍

2023-03-08 14:03 UTC, swiss-chris approved these changes

2023-03-09 10:20 UTC, sebisteiner approved these changes
LGTM 👍

2023-03-09 12:43 UTC, merged