feat(angular/tag): implement dark mode
sbb-design-systems/sbb-angular pull request #2005
Opened 2023-09-14 15:04 UTC by n1thushan

2023-09-21 10:41 UTC, mhaertwig requested changes
The colors of the badge were updated in Figma. Do you have time to update them? If so, please also double-check all colors in Standard, Lean and Dark Mode.

2023-09-26 09:00 UTC, mhaertwig requested changes

2023-09-26 09:00 UTC, mhaertwig commented on src/angular/styles/_typography.scss
> +  --sbb-color-white-alpha0: #{rgba(sbb.$sbbColorWhite, 0)};
```suggestion
```

2023-09-26 09:00 UTC, mhaertwig commented on src/angular/tag/tag.scss
>        :where(html.sbb-lean) & {
Braucht es dieses `:where(html.sbb-lean) & {` noch?

2023-09-26 09:13 UTC, matthiaswattingersbb approved these changes

2023-09-26 11:15 UTC, merged