feat(journey-maps) horizontal level switch
sbb-design-systems/sbb-angular pull request #2145
Opened 2024-01-23 12:30 UTC by swiss-chris

2024-01-24 07:13 UTC, mstankala commented on src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts
> +  private countdownTimer: ReturnType<typeof setTimeout>;
```suggestion
  private _countdownTimer: ReturnType<typeof setTimeout>;
```

2024-01-24 07:13 UTC, mstankala commented on src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts
> +  private autoCollapseTimeout = 5000; // 5000 ms
```suggestion
  private _autoCollapseTimeout = 5000; // 5000 ms
```

2024-01-24 07:14 UTC, mstankala commented on src/journey-maps/angular/components/level-switch/level-switch-horizontal.ts
> +  private focusMatchingButton(): void {
```suggestion
  private _focusMatchingButton(): void {
```

2024-01-24 07:51 UTC, mstankala commented
I feel like the animation when unfolding is different when a level is selected and when not. Could that be? 
When no level is selected, it looks very good. 
When a level is selected, there seems to be an overlay when unfolding.

2024-01-24 07:52 UTC, mstankala requested changes
It looks, like the animation when unfolding is different when a level is selected and when not. Could that be?
When no level is selected, it looks very good.
When a level is selected, there seems to be an overlay when unfolding.

2024-01-24 14:58 UTC, mstankala approved these changes
LGTM

2024-01-25 08:49 UTC, mhaertwig approved these changes
LGTM 👍

2024-01-25 08:50 UTC, merged