feat(journey-maps): add several new examples for journey maps client.…
sbb-design-systems/sbb-angular pull request #2217
Opened 2024-03-21 10:32 UTC by dev-ale

… delete full example

2024-03-22 09:27 UTC, mstankala commented on src/components-examples/journey-maps/angular/journey-maps-style-options/journey-maps-style-options-example.html
> +          <sbb-radio-button value="v1">v1</sbb-radio-button>
I would label the v1 radio button (legacy)
```suggestion
          <sbb-radio-button value="v1">v1 (legacy)</sbb-radio-button>
```

2024-03-22 09:29 UTC, mstankala commented on src/components-examples/journey-maps/angular/journey-maps-map-navigation/journey-maps-map-navigation-example.html
> +  <div class="row-1">
On narrow screens, the bounding box and zoom info is cut off. 
Can you force line breaks here?

2024-03-22 09:33 UTC, mstankala commented on src/components-examples/journey-maps/angular/journey-maps-routes-zones/journey-maps-routes-zones-example.ts
> + * @includeExtraFiles ../shared/config.ts,../shared/markers.ts,../shared/journey/be-sh.ts,../shared/journey/zh-be_wyleregg.ts,../shared/journey/zh-sh_waldfriedhof.ts,../shared/routes/biel-lyss.ts,../
This annotation @includeExtraFiles with routes and zones files, you need only in the Stackblitz example “SBB Map Routes & Zones”.
My suggestion: inside the shared/config.ts file, keep only the imports for zone routes only.
The remaining Consts values, copy directly into the concrete example:
- style_ids
- rail_colors
- ch_bounds
- poi_categories

2024-03-22 09:35 UTC, mstankala commented on src/components-examples/journey-maps/angular/index.ts
> +export {
Can we "force" somehow the order of the examples @kyubisation ?
I would like to habe the “SBB UI Options” as second example, after maps-basic.
Then “SBB Map Navigation” and the others.

2024-03-22 09:37 UTC, mstankala requested changes
please check my suggestions

2024-03-22 12:33 UTC, mstankala approved these changes
LGTM

2024-03-25 07:19 UTC, mhaertwig commented
Since it's not a functional change of journey-maps itself, please use `docs(journey-maps): ...` as a PR title. This affects versioning.

2024-03-25 15:25 UTC, mhaertwig approved these changes

2024-03-25 15:26 UTC, merged