fix(journey-maps): handle route teaser interaction
sbb-design-systems/sbb-angular pull request #2459
Opened 2024-12-12 09:56 UTC by andrinsibold

refs: ROKAS-2263
Issue: https://github.com/sbb-design-systems/sbb-angular/issues/2404

2024-12-12 10:33 UTC, swiss-chris commented
Es gibt jetzt 2 Examples mit Namen "Journey Maps - SBB Map POIs & Markers" mit jeweils ähnlichem Inhalt. Wir sollten entweder 2 vollig getrennte Examples machen mit eigenem Titel und eigenem Inhalt, oder beide in eines vereinen. Ich vermute, es wäre für den User einfacher verständlich, wenn es 2 separate wären, aber mit klar unterschiedlichem Zweck.

2024-12-12 10:34 UTC, swiss-chris requested changes
siehe Kommentar

2024-12-13 14:23 UTC, andrinsibold commented
> Es gibt jetzt 2 Examples mit Namen "Journey Maps - SBB Map POIs & Markers" mit jeweils ähnlichem Inhalt. Wir sollten entweder 2 vollig getrennte Examples machen mit eigenem Titel und eigenem Inhalt, oder beide in eines vereinen. Ich vermute, es wäre für den User einfacher verständlich, wenn es 2 separate wären, aber mit klar unterschiedlichem Zweck.

Ich habe zwei Beispiele miteinander gemerged und damit sollte es verständlicher für dne Benutzer sein.

2024-12-13 14:47 UTC, mstankala approved these changes
Thx, LGTM.

2024-12-16 08:34 UTC, mhaertwig approved these changes

2024-12-16 08:34 UTC, merged