feat(business): sidebar and icon sidebar
sbb-design-systems/sbb-angular pull request #600
Opened 2020-09-15 13:46 UTC by jeripeierSBB

2020-09-16 15:58 UTC, kyubisation requested changes
Fantastic work 👍 
I've added a few questions/comments

2020-09-16 15:58 UTC, kyubisation commented on src/angular-business/sidebar/sidebar.md
> +      <a sbbSidebarLink routerLink="/getting-started" routerLinkActive="sbb-sidebar-link-active"
Same as above `sbb-active`

2020-09-16 15:58 UTC, kyubisation commented on src/angular-business/sidebar/sidebar.md
> +<sbb-sidebar-container class="sbb-sidebar-after-header">
Should we add a convenience when the siderbar or icon-sidebar is placed immediately after the sbb-header?

2020-09-16 15:58 UTC, kyubisation commented on src/angular-business/sidebar/sidebar/sidebar.ts
> +  private _focusTrap: FocusTrap;
Place properties before the constructor

2020-09-17 06:53 UTC, jeripeierSBB commented on src/angular-business/sidebar/icon-sidebar/icon-sidebar.html
> +      style="display: none;"
It's because the label will never be displayed, it's only for accessibility. But I could move it to the style file?

2020-09-17 07:12 UTC, kyubisation commented on src/angular-business/sidebar/icon-sidebar/icon-sidebar.html
> +      style="display: none;"
display:none is also hidden from screen readers. Use the `cdk-visually-hidden` css class for content for screen readers only.

2020-09-17 08:52 UTC, kyubisation reviewed
Added documentation suggestion

2020-09-17 08:52 UTC, kyubisation commented on src/angular-business/sidebar/sidebar.md
> +<p>Random Content</p>
```suggestion
Whenever you add content between `<sbb-header>` and `<sbb-icon-sidebar-container>` elements or wrap
either in a component/element, add the css class `sbb-icon-sidebar-after-header` to the `<sbb-icon-sidebar-container>`
(e.g. `<sbb-icon-sidebar-container class="sbb-icon-sidebar-after-header">`).

```html
<sbb-header>...</sbb-header>
```

2020-09-17 08:52 UTC, kyubisation commented on src/angular-business/sidebar/sidebar.md
> +<p>Random Content</p>
```suggestion
Whenever you add content between `<sbb-header>` and `<sbb-sidebar-container>` elements or wrap
either in a component/element, add the css class `sbb-sidebar-after-header` to the `<sbb-sidebar-container>`
(e.g. `<sbb-sidebar-container class="sbb-sidebar-after-header">`).

```html
<sbb-header>...</sbb-header>
```

2020-09-17 11:35 UTC, kyubisation approved these changes
LGTM 👍 
@Frenggi Can you take a look at https://angular-staging.app.sbb.ch/600/business/components/sidebar

2020-09-18 16:59 UTC, Frenggi reviewed
@kyubisation @jeripeierSBB it looks good to me as well. I tried on desktop, tablet and mobile and it work very well and makes fun to use. :) Thank you very much.

2020-09-22 11:11 UTC, merged