refactor: remove deprecations
sbb-design-systems/sbb-angular pull request #629
Opened 2020-10-23 15:17 UTC by kyubisation

BREAKING CHANGE: We are removing internal properties and prefixing them
with _, if removing is not possible. These were never intended to be used by
consumers, however if you depended on these for some reason, reach out to us.

2020-10-27 15:59 UTC, jeripeierSBB requested changes
Thanks for

2020-10-27 15:59 UTC, jeripeierSBB commented on src/angular-public/textexpand/textexpand/textexpand.component.ts
> +  /** Refers to the textexpand-collapsed component istance. */
```suggestion
  /** Refers to the textexpand-collapsed component instance. */
```

2020-10-27 15:59 UTC, jeripeierSBB commented on src/angular-public/textexpand/textexpand/textexpand.component.ts
> +  /** Refers to the textexpand-expanded component istance. */
```suggestion
  /** Refers to the textexpand-expanded component instance. */
```

2020-10-27 15:59 UTC, jeripeierSBB commented on src/angular-public/textexpand/textexpand-collapsed/textexpand-collapsed.component.ts
> +    '[attr.hidden]': '_hidden',
```suggestion
    '[attr.hidden]': '_hidden ? true : null',
```

css styling won't work otherwise

2020-10-27 15:59 UTC, jeripeierSBB commented on src/angular-public/textexpand/textexpand-expanded/textexpand-expanded.component.ts
> +    '[attr.hidden]': '_hidden',
```suggestion
    '[attr.hidden]': '_hidden ? true : null',
```

css styling won't work otherwise

2020-10-27 16:10 UTC, jeripeierSBB commented on src/angular-public/datepicker/date-input/date-input.directive.ts
>      '[attr.min]': 'this.minAttr',
```suggestion
    '[attr.min]': 'this._minAttr',
```

2020-10-27 16:10 UTC, jeripeierSBB commented on src/angular-public/datepicker/date-input/date-input.directive.ts
>      '[attr.max]': 'this.maxAttr',
```suggestion
    '[attr.max]': 'this._maxAttr',
```

2020-10-28 13:55 UTC, kyubisation commented on src/angular-public/input/input/input.directive.ts
> +  errorState: boolean = false;
Yes, good point: https://github.com/sbb-design-systems/sbb-angular/blob/master/CODING_STANDARDS.md#typing

2020-10-29 07:32 UTC, jeripeierSBB requested changes

2020-10-29 07:32 UTC, jeripeierSBB commented on src/angular-core/forms/form-field-control.ts
> +   * An optional name for the control type that can be used to distinguish `mat-form-field` elements
introducing the next "mat" ;-)
```suggestion
   * An optional name for the control type that can be used to distinguish `sbb-form-field` elements
```

2020-10-29 07:32 UTC, jeripeierSBB commented on src/angular-core/forms/form-field-control.ts
> +   * `mat-form-field-type-{{controlType}}` to its root element.
```suggestion
   * `sbb-form-field-type-{{controlType}}` to its root element.
```

2020-10-29 10:29 UTC, merged