fix: improve usermenu
sbb-design-systems/sbb-angular pull request #640
Opened 2020-11-18 09:20 UTC by jeripeierSBB

2020-11-23 13:54 UTC, kyubisation requested changes
I requested some changes in the migration.
Other than that this is great work! 👍

2020-11-24 07:10 UTC, jeripeierSBB commented on src/angular-public/usermenu/usermenu-item.ts
> +    if (this._focusMonitor && origin) {
the only reason is, that I copied it from sbb header. But there in the constructor the focusMonitor is optional. So yes, I remove it :)

2020-11-24 11:00 UTC, kyubisation commented on src/angular-public/usermenu/usermenu.md
> +with comprehensive functionalities. The Usermenu should be placed in a site header, e.g. the `<sbb-header>`.
```suggestion
with comprehensive functionalities. The usermenu should be placed in a site header, e.g. the `<sbb-header>`.
```

2020-11-24 13:51 UTC, kyubisation approved these changes
LGTM 👍

2020-11-24 13:54 UTC, merged