refactor: migrate button
sbb-design-systems/sbb-angular pull request #745
Opened 2021-03-03 11:48 UTC by kyubisation

This PR migrates and refactors the button (and link) module. This is a
major refactoring which completely changes the button and link modules
and components. See the new button documentation for details.

2021-03-03 13:05 UTC, jeripeierSBB requested changes
First of all thanks for your great work! :-)

I think you missed to migrate showcase-merge to new buttons?

2021-03-03 13:05 UTC, jeripeierSBB commented on src/angular/styles/_typography.scss
> +  &.sbb-disabled {
if yes, also other variants should be changed

2021-03-03 14:02 UTC, kyubisation commented on src/components-examples/angular/button/button-overview/button-overview-example.css
> +:host-context(html:not(.sbb-lean)) .sbb-lean-only {
Will change to warning and add notice for hidden disabled button

2021-03-03 14:06 UTC, kyubisation commented on src/angular/styles/_typography.scss
> +    min-width: toEm(60 / $sizeFontDefault);
check if pxToEm exists

2021-03-04 09:47 UTC, jeripeierSBB requested changes

2021-03-04 09:47 UTC, jeripeierSBB commented on src/angular/button/button.md
> +<a routerLink="..." sbb-button>Button</button>
I'd use sbb-link here, not?

2021-03-04 09:59 UTC, jeripeierSBB approved these changes
LGTM :)

2021-03-04 10:38 UTC, merged