fix: don't reset height for sbb-textarea
sbb-design-systems/sbb-angular pull request #867
Opened 2021-08-26 10:04 UTC by kyubisation

Closes #862

2021-09-01 04:08 UTC, jeripeierSBB commented
I think in the merge showcase, the fix does not resolve the problem?
 
https://angular-staging.app.sbb.ch/867-merge/angular/components/textarea/examples

2021-09-07 14:30 UTC, jeripeierSBB requested changes
Maybe we should also enhance the markdown file?

Futhermore I think we should change the PR title to a refactor, because it doesn't really solve the issue, but it's better code

2021-09-07 14:30 UTC, jeripeierSBB commented on src/showcase/styles.scss
> +@include cdk.text-field();
import seems to be deprecated:

```
// @deprecated Use 'autosize' and 'autofill' instead.
@mixin text-field {
  @include text-field-autosize();
  @include text-field-autofill();
}
```

2021-09-07 14:30 UTC, jeripeierSBB commented on src/angular-public/typography.scss
> +@include cdk.text-field();
import seems to be deprecated:

```
// @deprecated Use 'autosize' and 'autofill' instead.
@mixin text-field {
  @include text-field-autosize();
  @include text-field-autofill();
}
```

2021-09-08 16:34 UTC, kyubisation commented
I updated the markdown files.
I would disagree; Previously the necessary CDK class was missing from the typography, which was causing an issue for the autosizing. This PR fixes that problem.

2021-09-09 08:55 UTC, merged