refactor: tooltip
sbb-design-systems/sbb-angular pull request #874
Opened 2021-09-06 15:46 UTC by kyubisation

2021-09-22 10:08 UTC, jeripeierSBB requested changes
Some more findings:
- it's not possible to reach the close icon or every other tooltip content by keyboard navigation
- merge symbols are missing (Were there really no component renames which have to be tracked by automatic migration?)
- In the showcase merge there are still usages of angular-business tooltip
- In components examples there is a angular-public tooltip usage
- toggling with space bar or enter key does not work (before merge it did)
- space between tooltip arrow and text in directive usage is too small, especially in standard. in 5k it does even collide

2021-09-22 10:08 UTC, jeripeierSBB commented on src/components-examples/angular/tooltip/tooltip-hover/tooltip-hover-example.html
> +<span
better use `<p>` here because it would scale in 4k and 5k (span does not and stays very small).

2021-09-22 10:08 UTC, jeripeierSBB commented on src/components-examples/angular/tooltip/tooltip-simple/tooltip-simple-example.html
> +<div>
I'd suggest to use `<p>` here so the 4k and 5k showcase looks better (scaled font size)

2021-09-22 15:55 UTC, kyubisation commented on src/angular/tooltip/tooltip.ts
> +export class TooltipComponent extends _TooltipComponentBase {
I would like to avoid that, since we previously had a SbbTooltipComponent. Also this is not a component that should be used.

2021-09-28 08:49 UTC, jeripeierSBB requested changes
- "esc" key seems to work not anymore
- hover color and focus color of cross icon in lean is not set

2021-09-28 08:49 UTC, jeripeierSBB commented on src/angular/schematics/ng-add/migrations/merge-refactor/tooltip-migration.ts
> +          'Please manually select a custom indicatorIcon: https://angular.app.sbb.ch/angular/components/button -->'
```suggestion
          'Please manually select a custom indicatorIcon: https://angular.app.sbb.ch/angular/components/tooltip -->'
```

2021-09-28 08:49 UTC, jeripeierSBB commented on src/angular/tooltip/tooltip-wrapper.scss
>    // padding + margin-top + border
```suggestion
```

2021-09-28 08:49 UTC, jeripeierSBB commented on src/angular/tooltip/tooltip-wrapper.scss
>      // padding + border
```suggestion
```

2021-09-28 15:51 UTC, jeripeierSBB approved these changes
LGTM

If you like to be outstandig ;), a unit test for the "esc" case would be very nice

2021-09-28 16:24 UTC, jeripeierSBB commented
two more findings: 
- tooltip "Tooltip Custom Content" example does focus the link on open instead of the cross icon. toggling is not possible.
- the focus style of the cross icon does somehow kick in with a delay.

2021-09-29 06:01 UTC, kyubisation commented
The logic focuses the first focusable element. I think that is the correct behavior for a persistent overlay.
The delay is probably caused by waiting for the animation to finish. This should ensure that the content is actually ready.

2021-09-29 11:24 UTC, merged