refactor: optimize header lean styles
sbb-design-systems/sbb-angular pull request #963
Opened 2021-12-03 14:48 UTC by kyubisation

2021-12-06 15:07 UTC, jeripeierSBB requested changes

2021-12-06 15:07 UTC, jeripeierSBB commented on src/angular/header-lean/header-menu.scss
> +  font-size: var(--sbb-header-lean-label-font-size);
more and more I see the font-size 21px, I think it's time to introduce a var?

2021-12-06 15:07 UTC, jeripeierSBB commented
yeah, a light header for standard design :-)

2021-12-07 13:45 UTC, kyubisation commented on src/angular/header-lean/header-menu-trigger.scss
>  .sbb-header-menu-trigger .sbb-header-menu-trigger-indicator.sbb-icon {
```suggestion
.sbb-header-menu-trigger .sbb-header-menu-trigger-indicator {
```

2021-12-07 15:50 UTC, jeripeierSBB approved these changes
LGTM

2021-12-07 15:51 UTC, merged