refactor: optimize breadcrumb styles
sbb-design-systems/sbb-angular pull request #968
Opened 2021-12-06 15:53 UTC by kyubisation

Work in progress

2021-12-07 12:25 UTC, jeripeierSBB requested changes

2021-12-07 12:25 UTC, jeripeierSBB commented on src/angular/breadcrumb/breadcrumbs.scss
> +  font-size: var(--sbb-font-size-smal);
```suggestion
  font-size: var(--sbb-font-size-small);
```

2021-12-07 16:38 UTC, kyubisation commented on src/angular/breadcrumb/breadcrumbs.scss
> +    height: calc(#{pxToRem(24)} * var(--sbb-scaling-factor));
```suggestion
    height: var(--sbb-icon-size-default);
```

2021-12-07 16:39 UTC, kyubisation commented on src/angular/breadcrumb/breadcrumbs.scss
> +    width: calc(#{pxToRem(24)} * var(--sbb-scaling-factor));
```suggestion
    width: var(--sbb-icon-size-default);
```

2021-12-08 08:54 UTC, jeripeierSBB requested changes

2021-12-08 08:54 UTC, jeripeierSBB commented on src/angular/breadcrumb/breadcrumbs.scss
> +      margin-top: calc(#{pxToRem(1)} * var(--sbb-scaling-factor));
```suggestion
      margin-top: calc(#{pxToRem(-1)} * var(--sbb-scaling-factor));
```

2021-12-08 14:55 UTC, jeripeierSBB approved these changes
LGTM

2021-12-08 15:11 UTC, merged